### ISSUE TITLE
Negative credits

### ISSUE THREAD

**Issue by Geogoeroe** [kartoza/prj.app#1031]
![image](https://user-images.githubusercontent.com/9982061/63650352-1ed08480-c74a-11e9-932f-73e0fb06a807.png)
Should this be possible?

**Comment by ann26** [comment]
hi @Geogoeroe currently yes, so you can issue as many certificates as you need and when your credits is not sufficient, you'll get negative credits. When your credits are not sufficient, you can only issue the certificate but cannot print it. But I think I'm going to change the logic so that it won't go negative.

**Comment by timlinux** [comment]
Can we close this now @ann26 ?

**Comment by Geogoeroe** [comment]
Ah, yes, sorry, didn't even reply properly...

Thanks a million, next course is coming up in a week already :-)

Erik.


Erik Meerburg
Directeur Geo Academie
06 - 2816 7631
erik@geo-academie.nl
GeoAcademieLogo <https://geo-academie.nl>
/Incompany trainingen in geo-informatie en GIS?
Dat kan natuurlijk op GeoFort, of bij u op locatie!/

**Comment by timlinux** [comment]
Nice - have fun @Geogoeroe !
