### ISSUE TITLE
Strange characters in PDF, not in HTML

### ISSUE THREAD

**Issue by Gustry** [kartoza/prj.app#1084]
On this page, the HTML rendering is fine http://changelog.qgis.org/en/qgis/section/data-providers-21/detail/79/?q=2.1

But the PDF contains some strange characters in the "Check your result'.

**Comment by NyakudyaA** [comment]
I think this is caused by the copy and paste from the libre office doc to mark down. They have to be cleaned manually

**Comment by timlinux** [comment]
Should be better now @Gustry ...though there is something else funny going on @ann26 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/178003/69485073-7e662b00-0e32-11ea-8434-703df81baf6d.png">


The :. looks wierd like it maybe had a number there or something - can you git blame to see what changes have happened to header renderering.

There are also a couple of empty rows in the requirements table - I'm never sure if I can just delete those or if there is missing content.

**Comment by ann26** [comment]
hi @Gustry I will investigate

hi @timlinux that's because the `q` parameter is missing from the url. 
if you use this url: `http://changelog.qgis.org/en/qgis/section/data-providers-21/detail/79/?q=2.1` you'll see the number shown but if you use this url: `http://changelog.qgis.org/en/qgis/section/data-providers-21/detail/79/` the number will be missing... I will think another more reliable way to solve the numbering....

**Comment by Gustry** [comment]
> hi @Gustry could you add the screenshot of what the strange character was? I checked on the pdf, I couldn't find the strange characters.

@ann26, @timlinux wrote: 
> Should be better now @Gustry

he fixed them

Thanks. I'm not sure if you want to keep the ticket open or not for the other bug.

**Comment by ann26** [comment]
Ah sorry, thanks @Gustry

**Comment by timlinux** [comment]
> http://changelog.qgis.org/en/qgis/section/data-providers-21/detail/79/ the number will be missing... I will think another more reliable way to solve the numbering....

Ah ok thanks
