### ISSUE TITLE
requirements table questions / tweaks

### ISSUE THREAD

**Issue by gubuntu** [kartoza/prj.app#847]
1. 'expectation' doesn't seem to be a generally useful field name. How about 'value'
1. What happens with the Notes field in the requirements table? It doesn't appear in the worksheet but space seems to be allocated to a column for it.

**Comment by NyakudyaA** [comment]
@sumandari I suggest you tackle issue 2 above because with 1 you would need to discuss it with Tim

Maybe we could have the Notes as a tooltip but we would need to let users know that if they hover over the requirements they will see a tooltip if available.

Do we need to print the notes into the PDF?
ping @zacharlie

**Comment by zacharlie** [comment]
It's hard to say whether the notes value would be useful in the printed materials because that would probably depend on the content, but yes if it is intended as a tooltip describing the column values then I would recommend using the notes as a description that subtext in the printed materials. I'm attaching a screenshot outlining my intention below.

![image](https://user-images.githubusercontent.com/64078329/102881831-1bd8c780-4456-11eb-9183-ffc1cf44f624.png)

In #1241 I asked that the value be dynamic so that content creators can change the table header value. I would say we also change the "Notes" to "Description" or "Field Description" to better describe it's purpose.

**Comment by sumandari** [comment]
The fixed has been deployed, I will close this ticket now
